prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    alerting:
      alertmanagers: []
    ruleSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    enableAdminAPI: false
    serviceMonitorSelector: {}
    ruleSelector: {}
    podMonitorSelector: {}
    probeSelector: {}

alertmanager:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

grafana:
  enabled: true
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  adminSecret:
    existingSecret: grafana-admin-secret
  adminUser: admin
  adminPassword: GRAFANA_PASSWORD_PLACEHOLDER
