apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::983169537692:role/pilar-challenge-eks-cluster-node-role
  mapUsers: |
    - userarn: arn:aws:iam::983169537692:user/aristeu13
      username: aristeu13
      groups:
        - system:masters
