apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilar-challenge
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pilar-challenge
  template:
    metadata:
      labels:
        app: pilar-challenge
    spec:
      containers:
        - name: pilar-challenge-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
      restartPolicy: Always
