apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pilar-challenge-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: pilar-challenge
  endpoints:
  - port: "http"
    interval: 30s
    path: /metrics
