apiVersion: v1
kind: Service
metadata:
  name: pilar-challenge-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-subnets: {{ .Values.publicSubnets }}
spec:
  selector:
    app: pilar-challenge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
