apiVersion: v1
kind: Service
metadata:
  name: pilar-challenge-service
spec:
  selector:
    app: pilar-challenge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
