name: Build and Push

on:
  workflow_call:


permissions:
  id-token: write
  contents: read

jobs:
  linting:
    uses: ./.github/workflows/pylint.yml
  build:
    name: Build and push to ecr
    runs-on: ubuntu-latest
    needs: [linting]

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::983169537692:role/Github-Role
        aws-region: us-east-1
        audience: sts.amazonaws.com

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: pilar-challenge
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
