name: K8s

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml

  k8s:
    name: k8s
    runs-on: ubuntu-latest
    needs: [terraform]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::983169537692:role/Github-Role
        aws-region: us-east-1
        audience: sts.amazonaws.com

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.29.1'
      id: install-kubectl

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: 'v3.15.2'
      id: install-helm

    - name: Get Kubeconfig
      run: |
        aws eks update-kubeconfig --name "pilar-challenge-eks-cluster" --region us-east-1
        echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
    
    - name: Add Prometheus Helm Repo
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update

    - name: Replace Grafana Password in Prometheus Values
      env:
        GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}
      run: |
        sed -i 's/GRAFANA_PASSWORD_PLACEHOLDER/'"$GRAFANA_PASSWORD"'/g' ./chart/prometheus-values.yaml
        cat ./chart/prometheus-values.yaml

    - name: Deploy Prometheus with Helm
      run: |
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack --values ./chart/prometheus-values.yaml

    - name: Create Values File
      run: |
        cat <<EOF > values-temp.yaml
        replicaCount: 1

        image:
          repository: 983169537692.dkr.ecr.us-east-1.amazonaws.com/pilar-challenge
          tag: ${{ github.sha }}
          pullPolicy: IfNotPresent
        EOF

    - name: Deploy Pilar Challenge with Helm
      run: |
        helm upgrade --install pilar-challenge ./chart --values values-temp.yaml --namespace default --timeout 15m --atomic

    - name: Get All Pods
      run: kubectl get pods --all-namespaces
