name: K8s

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
  k8s:
    name: k8s
    runs-on: ubuntu-latest
    needs: [terraform]

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::983169537692:role/Github-Role
        aws-region: us-east-1
        audience: sts.amazonaws.com

    - uses: azure/setup-kubectl@v3
      with:
        version: 'v1.29.1'
      id: install-kubectl

    - uses: azure/setup-helm@v4.2.0
      with:
        version: 'v3.15.2'
      id: install-helm

    - name: Get kubeconfig
      run: |
        aws eks update-kubeconfig --name "my-eks-cluster" --region us-east-1
        echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

    - name: Create values file
      env:
        GRAFANA_PASSWORD: ${{ secrets.GRAFANA_PASSWORD }}
      run: |
        cat <<EOF > values-temp.yaml
        replicaCount: 1

        image:
          repository: 983169537692.dkr.ecr.us-east-1.amazonaws.com/pilar-challenge
          tag: ${{ github.sha }}
          pullPolicy: IfNotPresent
        
        grafana:
          adminPassword: $GRAFANA_PASSWORD
        EOF

    - name: Deploy with Helm
      run: helm upgrade --install pilar-challenge ./chart --values values-temp.yaml --namespace default

    - name: teste
      run: kubectl get 
    
    - name: t
      run: kubectl logs prometheus-65b449f75f-4nkcn
