name: Terraform

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
  terraform:
    name: Build and push to ecr
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::983169537692:role/Github-Role
        aws-region: us-east-1
        audience: sts.amazonaws.com

    - uses: hashicorp/setup-terraform@v3

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      working-directory: infra

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: infra

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: infra

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      working-directory: infra
    
    - name: Terraform Apply
      id: apply
      run: terraform apply
      working-directory: infra